### PR TITLE
Merge the new docs

### PR DESCRIPTION
**Pull request by the94air**
Done! :smile: https://the94air.github.io/ziggy/

### CODE REVIEW

**Comment by ankurk91** [comment]
@the94air 
Don't you think that the PR should go to [gh-pages](https://pages.github.com/) branch?

**Comment by the94air** [comment]
But it **is** going to your gh-pages branch. what do you mean?

**Comment by DanielCoulbourne** [comment]
@ankurk91 Yeah as far as I can tell this is all good.

**Comment by ankurk91** [comment]
Yup, My bad. i though he has delete all of source code from the master branch.

**Comment by the94air** [comment]
:stuck_out_tongue_winking_eye:

**Comment by the94air** [comment]
should we leave the md version as is or..?

**Comment by ankurk91** [comment]
We should keep `html` version with `md` version in sync. Specially on new releases.

**Comment by the94air** [comment]
Sounds good. Thanks guys.

**Comment by DanielCoulbourne** [comment]
I'd like to look at something [like this](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3) at some point in the future so we can keep things in sync more easily.

**Pull request merged**
