### PR TITLE
Fix @routes Blade not working on some env (issue #115)

### PR DESCRIPTION
**Pull request by darron1217**
I made a pull request for issue #115

### CODE REVIEW

**Comment by inxilpro** [comment]
If any other service provider that's loaded before ziggy resolves the `blade.compiler` during boot, then the `afterResolving` hook won't fire. This is a very common pattern, and is even in the [Laravel docs](https://laravel.com/docs/5.5/blade#extending-blade). This PR is a good fix for that.

**Comment by darron1217** [comment]
@inxilpro Thanks for sharing information :)
I actually didn't understand why my fix is working.. haha

**Comment by DanielCoulbourne** [comment]
I'm going to merge this so people can pull down dev if they want, but I'm going to wait until I figure this and a few other things out before tagging a new release.

**Comment by DanielCoulbourne** [comment]
Thanks for finding a fix for this @darron1217

**Pull request merged**
