### PR TITLE
Allow usage of the generated routes in SSR-enabled environments

### PR DESCRIPTION
**Pull request by emielmolenaar**
I am using Ziggy in Nuxt.js, and the generated routes is causing errors on the server now because window isn't defined there. This commit should fix that :smiley:

### CODE REVIEW

**Comment by alfonsobries** [comment]
+1

**Comment by enzonotario** [comment]
Hi folks! Could you please tell me how are you using it with Nuxt? 

Thanks in advance!

**Comment by emielmolenaar** [comment]
I have created a Nuxt plugin in `plugins/ziggy.js` with the following content:

```
import Vue from 'vue'
import route from '@/node_modules/ziggy/dist/js/route'
import { Ziggy } from '@/mixins/ziggy/routes'

Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),
    }
});
```
Now you may generate a route by running `this.route(name, params);` in your Vue components.

**Comment by emielmolenaar** [comment]
Can we merge this please?

**Comment by mattstauffer** [comment]
@emielmolenaar Thanks for following up! Daniel, the maintainer, left Tighten and we've been a bit behind on taking over the maintenance responsibilities, because we've all been a bit slammed lately. But we're planning to triage issues and PRs and hopefully merge some PRs this week.

Thanks for your patience!

**Comment by emielmolenaar** [comment]
Ah right thanks for the explanation. No worries, thanks!

**Comment by emielmolenaar** [comment]
Awesome, thanks!

**Comment by bakerkretzmar** [comment]
Thanks for your patience! Hoping to tag a release including this later today.

**Comment by emielmolenaar** [comment]
No problem! Thank you for your efforts in merging this PR. Cheers!

**Pull request merged**
