### PR TITLE
Add support for whole object params

### PR DESCRIPTION
**Pull request by JesseLeite**
Adds support for whole object params, as discussed in #28.

```js
var event = {id: 123, name: 'World Series'};
var venue = {id: 456, name: 'Rogers Centre'};

route('events.venues.show', [event, venue])
// Outputs "http://myapp.dev/events/123/venues/456"
```

And support for mixed object and non-object params:

```js
var venue = {id: 456, name: 'Rogers Centre'};

route('events.venues.show', [123, venue])
// Outputs "http://myapp.dev/events/123/venues/456"
```

### Note on custom primary keys...

I realize a Laravel `Model` can be configured with a custom primary key, ie)

```php
class Post extends Model
{
    protected $primaryKey = 'uuid';
}
```

However, this could get complicated (especially if each model has a different primary key configuration) and might likely require some kind of Ziggy config array mapping.  I'm thinking this PR is a step in the right direction for now, at least for those who follow Laravel's `id` convention.  I would be interested in attempting custom primary keys in a separate PR though.  Thoughts?

### CODE REVIEW

**Comment by DanielCoulbourne** [comment]
You're a machine. Jeez. Lemme finish the PR I'm working on and read over this.

Thanks 👍

**Comment by DanielCoulbourne** [comment]
@JesseLeite Would you mind writing up a little documentation of this and #30 so I can tag them both into this release? I just need to get a contribution guide out real quick.

**Comment by JesseLeite** [comment]
@DanielCoulbourne Cool! Will do.

**Comment by JesseLeite** [comment]
Take a look, see what you think?

**Comment by DanielCoulbourne** [comment]
All about it dude.

**Comment by JesseLeite** [comment]
Cool thanks for your time!  Pretty cool little package you guys have created 👌

**Comment by DanielCoulbourne** [comment]
No problem at all! Thanks for your contributions. Threw you a little shoutout in the Readme.

**Comment by JesseLeite** [comment]
>Threw you a little shoutout in the Readme.

Didn't have to do that!  Appreciate the love though!

**Comment by mattstauffer** [comment]
FYI (heard this mentioned on twenty percent time as well) the eventual solution to this will need to use get route key name , not get key.

**Comment by mattstauffer** [comment]
(Get route key name is get key *unless* it's been explicitly customized which is most often done to customize implicit route model binding)

**Comment by JesseLeite** [comment]
@mattstauffer Oh interesting, I'll look into this 🙂

**Pull request merged**
