### PR TITLE
Allow optional id param

### LINKED ISSUE #206: Cannot use id param for query strings
I got a route with no param declared, and i'm using like this:

```
route('something', {type: 'a', id: 1});
```

* Current: `/something?0=1`
* Expected: `something?type=a&id=1`

Probably introduced by https://github.com/tightenco/ziggy/pull/143

### PR DESCRIPTION
**Pull request by Livijn**
Fixes a bug when using an optional id param, e.g.: `report/{type}/{id?}`

Fixes #206

### CODE REVIEW

**Comment by KuNman** [comment]
@Livijn can you make new composer package with this fix or @DanielCoulbourne can you accept it?

**Comment by mattstauffer** [comment]
I can merge this issue if folks say it works well for them. Can folks comment or leave emoji responses if this helps or hurts them?

Daniel is a bit behind on Ziggy because he’s got a lot going on!! but I’ll make sure the Tighten team picks it up going forward.

**Comment by KuNman** [comment]
I found it as fix for mentioned issue #206 , hope it works well cause atm I can't use param named as `id` which is quite frustrating.

**Comment by Livijn** [comment]
It works fine for me in 2 different projects and I did add some tests as well in the PR.

**Comment by KuNman** [comment]
Can you share what version of laravel and ziggy you use?
I'm trying to execute `route(url, {id: 1})` and it returns  `Router.urlParams: {0: 1}`. When I change key `id` to p.ex. `_id` it works - `Router.urlParams: {_id: 1}`.

**Comment by Livijn** [comment]
> Can you share what version of laravel and ziggy you use?
> I'm trying to execute `route(url, {id: 1})` and it returns `Router.urlParams: {0: 1}`. When I change key `id` to p.ex. `_id` it works - `Router.urlParams: {_id: 1}`.

I mean with this PR it works fine. You can require it in your composer.json: `"tightenco/ziggy": "dev-master#97f219bf1a0616bd4e6150b557b25617fef7893e"`

**Comment by KuNman** [comment]
Hmn, I removed `^0.9.0` and installed `dev-master#97f219bf1a0616bd4e6150b557b25617fef7893e`, `composer.lock` says 

```
"name": "tightenco/ziggy",
"version": "dev-master",
"source": {
    "type": "git",
    "url": "https://github.com/tightenco/ziggy.git",
    "reference": "97f219bf1a0616bd4e6150b557b25617fef7893e"
},
"dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/tightenco/ziggy/zipball/97f219bf1a0616bd4e6150b557b25617fef7893e",
    "reference": "97f219bf1a0616bd4e6150b557b25617fef7893e",
    "shasum": ""
},
```
I regenerated ziggy routes, cleared views cache and it works same as previously = crashed `urlParams`.
Should I do something else yet?

**Comment by Livijn** [comment]
That is the correct branch. What does your route look like and how are you referencing it with Ziggy?

**Comment by KuNman** [comment]
In `index.blade.php` I call  `@routes` in head section then in js I invoke it like that `const route = window.route;` and use like that `window.axios.get(route(url, body));`.

**Comment by Livijn** [comment]
> In `index.blade.php` I call `@routes` in head section then in js I invoke it like that `const route = window.route;` and use like that `window.axios.get(route(url, body));`.

What I meant was how does your route look like and how are you using that route?

**Comment by KuNman** [comment]
image

`Routes/api.php`
Screenshot 2020-04-07 at 20 34 42

We are talking about routes generated by Laravel's method for API resources.

**Comment by Livijn** [comment]
I don't see any optional id param.

**Comment by hydrogennz** [comment]
@mattstauffer I have tested this and it resolves the issue for routes with optional {id?} params. Thanks. 😄

**Comment by bakerkretzmar** [comment]
@Livijn thanks for your patience and for this fix. Just want to note here that this actually doesn't fix #206—that issue is a bug in trying to pass a _query_ param called `id`.

**Pull request merged**
