### PR TITLE
Implement qs.stringify to build query strings

### LINKED ISSUE #202: Inconsistency in query param with array value
Given a route with a query param key that has an array as a value
`route('route', ['foo' => ['a', 'b', 'c']])`

Laravel's route helper returns `/route?foo[0]=a&foo[1]=b&foo[2]=c` while ziggy returns `/route?foo=a,b,c`. When getting the param from the request object it handles it as a string and not an array.

### Currently installed Laravel version:
`5.7.*`

### Currently installed Ziggy version
`0.6.0`

### PR DESCRIPTION
**Pull request by evanbarter**
Fixes #202 and should be a better implementation than #219 as it properly stringifies objects and arrays.

### CODE REVIEW

**Comment by DanielCoulbourne** [comment]
@evanbarter I want to bring in QS at some point (been in the back of my mind for a while) 

Would you mind re-working the bit of this PR that conflicts with #229 as well as either pulling in the test from #219 or writing your own test to prove that this works?

**Comment by DanielCoulbourne** [comment]
Also please rebase off the latest master as that will allow the CI build to pass.

**Comment by DanielCoulbourne** [comment]
Ok I wasnt able to push to the branch but I figured something out and merged #244

**Comment by evanbarter** [comment]
@DanielCoulbourne Thank you, sorry I wasn't able to get to this sooner!

**Comment by reinink** [comment]
FWIW, this was a breaking change, and broke my app when I updated. 😂

Given this code, where `users` is an array of user ids:

```js
route('endpoint', { users: users })
```

Previous behaviour:

```
/endpoint?users=80,81,82,83,84,85
```

New behaviour:

```
/endpoint?users[0]=80&users[1]=81&users[2]=82&users[3]=83&users[4]=84&users[5]=85
```

My app was relying on the previous behaviour. 😬

Either way, all good now. I've fixed things on my end. Just thought I'd let you know. 💪

**Comment by Thinkro** [comment]
@reinink Sorry for pinging you on this a few years later. But how did you choose to handle this? I'm not sure if i should do `/endpoint?users=80,81,82,83,84,85` or `/endpoint?users[0]=80&users[1]=81&users[2]=82&users[3]=83&users[4]=84&users[5]=85
`

**Pull request closed without merging**
