### PR TITLE
Check for falsy value as well, fixes #186

### LINKED ISSUE #186: Cannot read property 'id' of null in Vue Component
### Current Behavior
route('product.show', {slug: form.slug}) returns "/product/my-product" which is correct, BUT it throws an exception 
```javascript
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'id' of null" 
```
generated in hydrateUrl() method:
```javascript
...
paramsArrayKey++;
if (typeof tags[key] !== 'undefined') {
    delete _this2.queryParams[key];
    return tags[key].id || encodeURIComponent(tags[key]);
}
...
```

### Currently installed Laravel version:
`5.7.12`

### Currently installed Ziggy version
`0.6.9`

### Route from Laravel Routes file.
```php
Route::get('product/{slug}', 'ProductController@show')->name('product.show');
```
### Contents of Ziggy.namedRoutes
```javascript
{'product.show': {uri: "product/{slug}", methods: ["GET", "HEAD"], domain: null}}
```

### Ziggy call in context
```javascript
<a :href="route('product.show', {slug: data.slug})">Product name</a>
```

### PR DESCRIPTION
**Pull request by ankurk91**
We were just checking for undefined values, while we should also check for `false`, `null` values as well.
fixes #186

### CODE REVIEW

**Comment by jakebathman** [comment]
Thanks for this fix, Ankur! 

Travis build/test is failing because of some `phpunit` version issues, but I've checked this out locally and confirmed `phpunit` and `mocha` tests are passing.

**Comment by ankurk91** [comment]
@DanielCoulbourne 
Is it possible to merge this PR?
 It is a very small change and has been approved already.

**Comment by ankurk91** [comment]
Any chance to get this merged with Laravel v6.x support

**Comment by DanielCoulbourne** [comment]
@ankurk91 I will get this merged tomorrow along with a few other PRs. Thanks for your work on this.

**Comment by jakebathman** [comment]
Thanks so much @ankurk91!

**Pull request merged**
