### PR TITLE
Add end and start symbols to regex for current check

### PR DESCRIPTION
**Pull request by thoresuenert**
Resolves Issue #213

### CODE REVIEW

**Comment by jakebathman** [comment]
Awesome, thanks for this fix. 

Travis builds are failing as expected (fix is in #215) but Mocha tests are passing locally.

**Comment by thoresuenert** [comment]
@jakebathman do you know when this will be merged?

**Comment by DanielCoulbourne** [comment]
Hey all. I didn't have 20% time last week but I'll sort out this, along with a bunch of other PRs on friday. Any help the community can offer to get these PRs ready for merge (making sure tests are passing and that we are rebased off the latest master) would be a huge help.

**Comment by DanielCoulbourne** [comment]
I don't have push permission for this PR so I duplicated it as #235

**Pull request closed without merging**
