### PR TITLE
auto compile js file when laravel routes are changed

### PR DESCRIPTION
**Pull request by ctf0**
https://github.com/tightenco/ziggy/issues/22

### CODE REVIEW

**Comment by mattstauffer** [comment]
Three problems here: 

First, the modified time on a folder doesn't change when the contents of its child files are changed.

Second, this slows down the entire app by adding this check every time the app is loaded.

Third, this won't update the js file in time if it's needed by a build tool; I could change all of my routes file and never open the app and this would never run, so the build tool would never get the updated javascript.

**Comment by ctf0** [comment]
> First, the modified time on a folder doesn't change when the contents of its child files are changed.

actually on my mac the routes folder time gets changed every time i change any file under it, and i even have nested folders for each route group.

> Second, this slows down the entire app by adding this check every time the app is loaded.

it doesnt cost that much, but if u have a better idea, am all ears.

> I could change all of my routes file and never open the app and this would never run.

we can then have a cmnd that does that.

**Comment by DanielCoulbourne** [comment]
@ctf0 I don't think we are going to merge this for a few reasons:

1) We don't want to have all these File checking operations appended to every request to the app. We are trying to minimize impact to load-time. In my mind one of the only reasons someone would opt to precompile this JS on their own is to avoid the minor performance hit of our blade directive. In that case, I think adding a bunch of file operations to the beginning of their app is kind of sketchy.

2) I think this is something that should only be fired in the local environment during development. I don't love the idea of tying into mix, but we already experimented with checking Route files for dirtiness and we opted to avoid that.

3) I think it's weird that we have a `src/js/route.js` file being compiled into PHP to be re-exported to another JS file. It just makes me feel weird personally.

**Comment by ctf0** [comment]
actually this wont work for 2 reasons
1- watching the route folder is not effective, because what about the packages that register its own routes?
2- calling `app(BladeRouteGenerator::class)->generate()` outside of the blade dir, give empty array, not sure why through 🙄

**Pull request closed without merging**
