### PR TITLE
Fix various bugs with URL building.

### PR DESCRIPTION
**Pull request by DanielCoulbourne**

### CODE REVIEW

**Comment by DanielCoulbourne** [comment]
Fixes #106

**Comment by DanielCoulbourne** [comment]
Fixes #110

**Comment by ankurk91** [comment]
@DanielCoulbourne
can you tag a new version ?

**Comment by DanielCoulbourne** [comment]
Will do later tonight

**Comment by the94air** [comment]
I will handle the version drop-down for the docs

**Pull request merged**
