### PR TITLE
Add compatibility with Laravel 6

### PR DESCRIPTION
**Pull request by victorlap**
This pull request adds compatibility with Laravel 6

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks for this pull request! Have you tested it out yet? Thanks!

**Comment by victorlap** [comment]
Hi, yes I tested it out in a real application (using Laravel dev-master) and everything seems to be working as expected. I had to change the array_ and str_ helper functions to use the class-based equivalent though.

**Comment by mattstauffer** [comment]
Great, @DanielCoulbourne will take a look at this shortly--thanks!

**Comment by jakebathman** [comment]
Thanks @victorlap!

**Comment by victorlap** [comment]
Hi thanks for merging!

Can you release a new version now that Laravel 6.0 is out?

**Pull request merged**
