### PR TITLE
Allow publishing config

### PR DESCRIPTION
**Pull request by ankurk91**
This PR will allow publishing default configs. User no need to manually create config file.

These configs will not be used by package unless user publish it.
We can publish config with this command:
```
php artisan vendor:publish --provider="Tightenco\Ziggy\ZiggyServiceProvider" --tag="config"
```

**todo**
* Documentation on how to publish config in readme.md
* Document each of the config property in `config/ziggy.php`, what they do.
* At-least add a note about using one either `blacklist` or `whitelist` property.

### CODE REVIEW

**Comment by DanielCoulbourne** [comment]
I'm still not really into publishing configs. Sorry haha.

**Comment by JoshuaDoshua** [comment]
Any chance opinions on this has changed? I see configs everywhere, but no actual config file.

If its still:
> I'm still not really into publishing configs. Sorry haha.

Would you consider an alternative of just creating a config file in this package that sets the defaults so it can be easily referenced?

Happy to open a new PR or update this one; tagging @bakerkretzmar since it's an old Issue and you seem to be pretty active here

**Comment by bakerkretzmar** [comment]
Sure, and I actually have a branch locally where I've played with this. I don't love it either but it is nice to have everything listed in one place. I'll try to work on it but I'd be open to a PR too 👍🏻

**Comment by WalterWoshid** [comment]
> I'm still not really into publishing configs. Sorry haha.

Why, just why? Looking up the config in the docs or looking up the code in the vendor directory is just stupid.

**Pull request closed without merging**
