### PR TITLE
Update route generator to append routes to existing Ziggy object

### LINKED ISSUE #165: Feature Request: Appending routes
I can see a few situations where allowing multiple calls to @routes would be useful.
For example when I have a lot of shared routes for everyone and a few for just admins.

Here is an example config file:

    return [
        'whitelist' => [
            'api.*',
        ],
        'groups' => [
            'admin' => [
                'admin.*',
            ],
        ],
    ];

And blade directives:

    @routes()
    @routes('admin')

I would expect this to load both `api.*` and `admin.*` routes instead of just loading the last command used.
This will be especially helpful, when the main routes are generated using `artisan ziggy:generate` command and the admin routes are only added in admin panel for users that are already logged in.

### PR DESCRIPTION
**Pull request by mattisbones**
This commit resolves #165 by modifying additional calls to the `@routes()` directive to merge additional routes into the existing Ziggy object.

### CODE REVIEW

**Comment by Robert-Hansen** [comment]
any chance this could be merged i'm working on a project where i ran into problems having multiple Ziggy objects on the window looks like this would fix it @DanielCoulbourne

**Comment by DanielCoulbourne** [comment]
I'll look more closely at this tonight.

**Comment by Robert-Hansen** [comment]
any update?

**Comment by DanielCoulbourne** [comment]
Thanks for your patience. Merged and will tag soon.

**Pull request merged**
