### PR TITLE
Add group option to ziggy:generate command

### PR DESCRIPTION
**Pull request by mpskovvang**
This PR adds a `--group` option to the generate routes command.

# Why?
If an application relies on multiple route groups, it is useful to generate multiple files to build different JS entries targeting different user groups.

A typical example could be a `resources/routes/default.js` containing public routes and a `resources/routes/admin.js` with admin-related routes. In the Laravel Mix (or similar) pipeline, you can import the necessary routes for your specific entry.

### CODE REVIEW

**Comment by jakebathman** [comment]
This is a nice addition Martin! Gonna approve the PR and get it tagged for release once @DanielCoulbourne has had a chance to look at it when he's back next week.

**Comment by mpskovvang** [comment]
I'm glad you like the addition as well. Thanks for a really great package! 👍

**Comment by rodrigopedra** [comment]
Hi @jakebathman and @DanielCoulbourne any chance it gets tagged?

Had just cloned the repo to add this option and then I see the code was already there =D

By the way, thanks @mpskovvang for adding this, just what I need for a project

**Comment by geodeveloper** [comment]
Hi @DanielCoulbourne . When this will be tagged? It's really a must have feature.

**Pull request merged**
